@test size(full_dataset("noint2")) == (1,12)
@test size(full_dataset("wampler3")) == (6,12)
@test size(full_dataset("longley")) == (7,12)
@test size(full_dataset("pontius")) == (3,12)
@test size(full_dataset_compare("noint1")) == (1,12)
@test size(full_dataset_compare("wampler5")) == (6,12)
@test size(full_dataset_compare("norris")) == (2,12)
@test size(full_dataset_compare("pontius")) == (3,12)